const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{interfaz_01: 0},
	{ArrastrarYSoltar: 0},
	{tesoros: 0},
	{marcador_1: 0},
	{marcador_2: 0},
	{marcador_3: 0},
	{Mouse: 0},
	{ControlTáctil: 0},
	{Teclado: 0},
	{bool_mouse: 0},
	{btn_nueva_division: 0},
	{id: 0},
	{box_dividendo: 0},
	{btn_verificar: 0},
	{box_rdivisor: 0},
	{box_cociente: 0},
	{box_residuo: 0},
	{Audio: 0},
	{Enunciado: 0},
	{sprite_enunciado: 0},
	{sprite_Text_divisor: 0},
	{portada: 0},
	{btn_iniciar: 0},
	{Lena_barco_01: 0},
	{Parpadeo: 0},
	{Lena_celebra: 0},
	{cell_width: 0},
	{cell_height: 0},
	{x_ini_matriz: 0},
	{y_ini_matriz: 0},
	{dividendo: 0},
	{divisor: 0},
	{cociente: 0},
	{residuo: 0},
	{tamaño_entrada_texto: 0},
	{fila: 0},
	{columna: 0}
];

self.InstanceType = {
	interfaz_01: class extends self.ISpriteInstance {},
	tesoros: class extends self.ISpriteInstance {},
	marcador_1: class extends self.ISpriteInstance {},
	marcador_2: class extends self.ISpriteInstance {},
	marcador_3: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ControlTáctil: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	btn_nueva_division: class extends self.IButtonInstance {},
	box_dividendo: class extends self.ITextInputInstance {},
	btn_verificar: class extends self.ISpriteInstance {},
	box_rdivisor: class extends self.ITextInputInstance {},
	box_cociente: class extends self.ITextInputInstance {},
	box_residuo: class extends self.ITextInputInstance {},
	Audio: class extends self.IInstance {},
	Enunciado: class extends self.ITextInstance {},
	sprite_enunciado: class extends self.ISpriteInstance {},
	sprite_Text_divisor: class extends self.ISpriteFontInstance {},
	portada: class extends self.ISpriteInstance {},
	btn_iniciar: class extends self.ISpriteInstance {},
	Lena_barco_01: class extends self.ISpriteInstance {},
	Lena_celebra: class extends self.ISpriteInstance {}
}